# SPDX-FileCopyrightText: 2025 Dyne.org foundation
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "Zenroom"
SPDX-PackageSupplier = "Denis Roio <jaromil@dyne.org>"
SPDX-PackageDownloadLocation = "https://github.com/dyne/Zenroom"

[[annotations]]
path = [
    "src/**",
    "bindings/**",
    "test/**",
    "docs/**",
    ".github/**",
    "build/*",
    ".gitattributes",
    "compile_flags.txt"
]
precedence = "override"
SPDX-FileCopyrightText = "2017-2025 Dyne.org foundation"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["lib/lua54/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "1994-2024 Lua.org, PUC-Rio"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["lib/milagro-crypto-c/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["lib/pqclean/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Léo Ducas, Eike Kiltz, Tancrède Lepoint, Vadim Lyubashevsky, Gregor Seiler, Peter Schwabe, Damien Stehlé"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["lib/ed25519-donna/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Andrew M. <liquidsun@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["lib/mlkem/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2025 The mlkem-native project authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["src/varint.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2024 Joshua J Baker"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["lib/zstd/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2016-present, Facebook, Inc."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["lib/longfellow-zk/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Google LLC."
SPDX-License-Identifier = "Apache-2.0"

