site_name: Project-name
site_url: https://decodeproject.github.io/ProjectName
repo_url: https://github.com/decodeproject/redroom
site_author: Jaromil
site_description: ProjectName is powered by ... to ...
copyright: Copyright (C) 2019 by the <a href="https://dyne.org">Dyne.org foundation</a>. The source code is licensed <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3</a>.
keywords: some, key, tags

extra:
  links:
    releases: https://files.dyne.org/projectname
    docker: https://hub.docker.com/r/dyne/projectname
    quickstart: https://github.com/decodeproject/projectname/wiki
    forum: https://lists.dyne.org
  drift_handle: s64nd7w43g53
  nav:
    subtitle: This is an awesome project
    logo: null # /img/redroom-trans.png
    og_image_large: /img/logo-trans.png


plugins: []

extra_css:
  - //fonts.googleapis.com/css?family=Montserrat&display=swap
  - css/custom.css

markdown_extensions:
  - admonition
  - codehilite

theme:
  name: null
  custom_dir: 'mkdocs-dyne-theme/'
